version: "3"
services:
  pds:
    build: 
      context: .
    environment:
      - PDS_HOSTNAME=pds.bossett.social
      - PDS_ADMIN_EMAIL=bossett@bossett.io
    volumes:
      - ./pdsdata:/pds